name: minesweeper
services:
  app:
    build:
      context: .
    command: sh docker/start.sh
    volumes:
      - .:/app:cached
    env_file:
      - web.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: minesweeper
    ports:
      - "3306:3306"
    volumes:
      - ./db_volume/mysql_data:/var/lib/mysql
      - ./db_volume/mysql_config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
   